import itemsData from '@shared/items_data.json';

const GAME_ITEM_ICONS: Record<string, string> = {
  'poké ball': 'poke-ball.png',
  'poke ball': 'poke-ball.png',
  'great ball': 'great-ball.png',
  'super ball': 'ultra-ball.png',
  'ultra ball': 'ultra-ball.png',
  'master ball': 'master-ball.png',
  'idle ball': 'cherish-ball.png',
  'pixel ball': 'poke-ball.png',
  'potion small': 'potion.png',
  'small potion': 'potion.png',
  'potion': 'potion.png',
  'great potion': 'hyper-potion.png',
  'ultra potion': 'max-potion.png',
  'max potion': 'max-potion.png',
  'hyper potion': 'hyper-potion.png',
  'super potion': 'super-potion.png',
  'ultimate potion': 'max-potion.png',
  'potion_small': 'potion.png',
  'potion_great': 'super-potion.png',
  'potion_super': 'super-potion.png',
  'potion_hyper': 'hyper-potion.png',
  'potion_ultra': 'hyper-potion.png',
  'potion_max': 'max-potion.png',
  'potion_ultimate': 'max-potion.png',
  'revive': 'revive.png',
  'revive basic': 'revive.png',
  'minor revive': 'revive.png',
  'max revive': 'max-revive.png',
  'revive_minor': 'revive.png',
  'revive_basic': 'revive.png',
  'revive_max': 'max-revive.png',
  'capsule_basic': 'poke-ball.png',
  'capsule_great': 'great-ball.png',
  'capsule_super': 'ultra-ball.png',
  'capsule_ultra': 'ultra-ball.png',
  'capsule_master': 'master-ball.png',
  'rare candy': 'rare-candy.png',
  'escape rope': 'escape-rope.png',
  'elixir': 'elixir.png',
  'antidote': 'antidote.png',
  'paralyze heal': 'paralyze-heal.png',
  'awakening': 'awakening.png',
  'burn heal': 'burn-heal.png',
  'ice heal': 'ice-heal.png',
  'full heal': 'full-heal.png',
  'repel': 'repel.png',
  'super repel': 'super-repel.png',
  'max repel': 'max-repel.png',
  'x attack': 'x-attack.png',
  'x defense': 'x-defense.png',
  'x speed': 'x-speed.png',
  'x accuracy': 'x-accuracy.png',
  'dire hit': 'dire-hit.png',
  'isca': 'poke-ball.png',
  'vara de pesca': 'old-rod.png',
  'vara de pesca velha': 'old-rod.png',
  'vara de pesca boa': 'good-rod.png',
  'vara de pescasuper': 'super-rod.png',
  'vara de pesca super': 'super-rod.png',
  'adubo mineral': 'star-piece.png',
  'pedra de fogo': 'fire-stone.png',
  'pedra agua': 'water-stone.png',
  'pedra relampago': 'thunder-stone.png',
  'pedra folha': 'leaf-stone.png',
  'pedra lua': 'moon-stone.png',
  'pedra sol': 'sun-stone.png',
  'pedra noturno': 'dusk-stone.png',
  'pedra brilho': 'shiny-stone.png',
  'pedra gelo': 'ice-stone.png',
  'pedra acido': 'hard-stone.png',
  'pedra dragao': 'dragon-scale.png',
  'pedra obsidiana': 'hard-stone.png',
  'pedra antiga': 'hard-stone.png',
  'pedra casulo': 'hard-stone.png',
  'pedra metal': 'hard-stone.png',
  'pedra electirizer': 'hard-stone.png',
  'pedra magmarizer': 'hard-stone.png',
  'pedra serrada': 'hard-stone.png',
  'pedra do crepusculo': 'hard-stone.png',
  'licenca de reespecializacao': 'exp-share.png',
  'reference enchanted gem': 'star-piece.png',
  'reference future orb': 'nugget.png',
  'reference rubber ball': 'poke-ball.png',
  'reference strange thing': 'nugget.png',
  'reference earth ball': 'poke-ball.png',
  'reference sandbag': 'poke-ball.png',
  'reference bottles of poison': 'potion.png',
  'reference psychic spoon': 'nugget.png',
  'reference rare fossil': 'helix-fossil.png',
  'reference dragon scale': 'dragon-scale.png',
  'reference metal coat': 'metal-coat.png',
  'reference moon stone': 'moon-stone.png',
  'reference fire stone': 'fire-stone.png',
  'reference water stone': 'water-stone.png',
  'reference thunder stone': 'thunder-stone.png',
  'reference leaf stone': 'leaf-stone.png',
  'reference sun stone': 'sun-stone.png',
  'reference ice stone': 'ice-stone.png',
  'reference dusk stone': 'dusk-stone.png',
  'reference shiny stone': 'shiny-stone.png',
  'stone fire': 'fire-stone.png',
  'stone water': 'water-stone.png',
  'stone thunder': 'thunder-stone.png',
  'stone leaf': 'leaf-stone.png',
  'stone moon': 'moon-stone.png',
  'stone sun': 'sun-stone.png',
  'stone ice': 'ice-stone.png',
  'stone dusk': 'dusk-stone.png',
  'stone shiny': 'shiny-stone.png',
  'stone ancient': 'hard-stone.png',
  'stone bug': 'hard-stone.png',
  'nugget': 'nugget.png',
  'big nugget': 'nugget.png',
  'pearl': 'pearl.png',
  'big pearl': 'big-pearl.png',
  'stardust': 'stardust.png',
  'star piece': 'star-piece.png',
  'helix fossil': 'helix-fossil.png',
  'dome fossil': 'dome-fossil.png',
  'old amber': 'old-amber.png',
  'exp share': 'exp-share.png',
  'lucky egg': 'lucky-egg.png',
  'amulet coin': 'amulet-coin.png',
  'odor sleuth': 'poke-ball.png',
};

const BASE_URL = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/';

export function getItemIcon(nameOrId: string): string {
  if (!nameOrId) return '';
  const n = nameOrId.toLowerCase().trim();

  const direct = GAME_ITEM_ICONS[n];
  if (direct) return `${BASE_URL}${direct}`;

  const found = (itemsData as any[]).find((i: any) => i.name.toLowerCase() === n || i.id?.toString() === n);
  if (found?.icon) return found.icon;

  if (n.includes('pheromone')) return `${BASE_URL}sweet-heart.png`;
  if (n.includes('fragment')) return `${BASE_URL}star-piece.png`;
  if (n.includes('revive')) return `${BASE_URL}revive.png`;
  if (n.includes('potion')) return `${BASE_URL}potion.png`;
  if (n.includes('stone') || n.includes('pedra')) return `${BASE_URL}hard-stone.png`;
  if (n.includes('ball') || n.includes('capsule')) return `${BASE_URL}poke-ball.png`;

  return `${BASE_URL}${n.replace(/[éè]/g, 'e').replace(/\s+/g, '-')}.png`;
}
